name: xneusm
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - networkx=3.1
  - pandas=1.3.5
  - pillow=8.4.0
  - scipy=1.7.3
  - matplotlib=3.5.1
  - numpy=1.21.2
  - tqdm=4.62.3
  - pytorch=1.8.2
  - scikit-learn=0.24.2
  - ipykernel=6.4.1